<?php
/**
 * Created by PhpStorm.
 * User: Sam
 * Date: 2017/1/4
 * Time: 下午9:06
 */

namespace backend\controllers;


use app\models\SmsAdmin;
use Yii;
use app\models\Books;
use yii\data\SqlDataProvider;
use yii\web\Controller;
use yii\grid\GridView;
use app\models\Source;
use yii\web\UploadedFile;
use yii\web\Webservice;
//微信框架引入方式
include dirname(dirname(__FILE__)).'/libs/LaneWeChat/lanewechat.php';
include dirname(dirname(__FILE__)).'/libs/LaneWeChat/core/source.lib.php';
include dirname(dirname(__FILE__)).'/libs/LaneWeChat/core/templatemessage.lib.php';
include dirname(dirname(__FILE__)).'/libs/LaneWeChat/core/advancedbroadcast.lib.php';
include dirname(dirname(__FILE__)).'/libs/LaneWeChat/core/responseinitiative.lib.php';
include dirname(dirname(__FILE__)).'/libs/LaneWeChat/core/usermanage.lib.php';
class BookController extends Controller
{

    public function beforeAction($action)
    {
        if (empty(Yii::$app->user->identity)) {
            return $this->redirect(['/default/login']);
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function init()
    {
        parent::init();
    }

    public function actionIndex()
    {
        $this->layout = 'main';
        $searchModel = new Books();
        $query = Yii::$app->request->queryParams;
        $sql_parms = 'where 1=1';
        if (!empty($query['Books']['name'])) {
            $sql_parms .= " and name like '%" . $query['Books']['name'] . "%'";
        }

        if (isset($query['Books']['status'])) {
            $sql_parms .= " and status = '" . $query['Books']['status'] . "'";
        }
        $sql = "select * from wechat_books  " . $sql_parms . " order by id desc";
        $command = Yii::$app->db->createCommand('SELECT COUNT(*) FROM wechat_books ' . $sql_parms);
        $count = $command->queryScalar();

        $dataProvider = new SqlDataProvider([
            'sql' => $sql,
//            'params' => [':status' => 1],
            'totalCount' => $count,
            'pagination' => [
                'pageSize' => 15,
            ],
            'sort' => [
                'attributes' => [
                    'id',
                ],
            ],
        ]);

        GridView::widget([
            'dataProvider' => $dataProvider,
        ]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'query' => $query,
        ]);
    }

    public function actionDelete()
    {
        $query = Yii::$app->request->queryParams;
        $id = $query['id'];
        $data = Books::findOne($id);
        $data->delete();
        Yii::$app->cache->delete('index');
        return $this->redirect(['index']);
    }
    public function actionPush()
    {
        $this->layout = 'main';
        $model = new Source();
        $query = Yii::$app->request->queryParams;
        $conn = Yii::$app->db;
        if(!empty(Yii::$app->request->post())) {
            $params = Yii::$app->request->post();
            $id = $params['id'];
            //print_r($params);exit;
            //图片素材ID数组
            $media_id = [];
            //上传图片
            $pic = $this->setImageInformation($_FILES);
            foreach ($pic as $key => $value) {
                //图片（image）、语音（voice）、视频（video）和缩略图（thumb）
                //上传图片素材
                $upload = \LaneWeChat\Core\Media::addmaterial($value,'image');
                //上传图片素材成功
                if(!empty($upload['url'])){
                    $media_id[$key] = $upload['media_id'];
                    if(is_file($value)){
                        //删除上传的图片
                        unlink($value);
                    }
                }
            }
            //echo "media_id:";
            //var_dump($media_id);
            $send = [];
            $id_arr = explode(',', $id);
            foreach ($media_id as $k => $v) {
                $new['thumb_media_id'] = $v;
                $new['title'] = $params['title'][$k];
                $new['content'] = !empty($params['content'][$k])?$params['content'][$k]:"";
                //默认值
                $new['author'] = "图书管理员";
                $new['digest'] = "";
                $new['show_cover_pic'] = "0";
                $new['content_source_url'] = "";
                $send[] = $new;
                $mysql[] = "('".$params['title'][$k]."','".$v."','图书管理员','','0','".$new['content']."','','".time()."','','0','0')";
            }
            //echo "</br>send:";
            //var_dump($send);
            //$str = implode(',', $mysql);

            //$sql = "INSERT INTO wechat_source (title,thumb_media_id,author,digest,show_cover_pic,content,content_source_url,time,file,isdeleted,status) VALUES ".$str;
            if(count($send)>0){
                $s_id = [];
                //批量插入素材管理
                foreach ($mysql as $key => $value) {
                    # code...
                    $sql = "INSERT INTO wechat_source (title,thumb_media_id,author,digest,show_cover_pic,content,content_source_url,time,file,isdeleted,status) VALUES ".$value;
                    $command = $conn->createCommand($sql);
                    $data = $command->execute();
                    $s_id[] = $conn->getLastInsertID();
                }
                $news = \LaneWeChat\Core\Media::addnews($send);
                if(!empty($news['media_id'])){
                    $users = \LaneWeChat\Core\UserManage::getFansList();
                    $userlist = $users['data']['openid'];
                    $result = \LaneWeChat\Core\AdvancedBroadcast::sentNewsByOpenId($userlist,$news['media_id']);
                    if($result['errcode']==0){
                        $command = $conn->createCommand("update wechat_source set status = 1 where id in(".implode(',', $s_id).")");
                        $data = $command->execute();
                        $title = !empty($params['name'])?$params['name']:data('Y-m-d',time())."新书通报";
                        $notice_sql = "INSERT INTO wechat_notice (title,date,memo) VALUES ('".$title."','".time()."','".$params['memo']."')";
                        $command = $conn->createCommand($notice_sql);
                        $data = $command->execute();
                        $notice_id = $conn->getLastInsertID();
                        $update_book = $conn->createCommand("update wechat_books set status = 1 ,n_id = ".$notice_id." where id in(".$id.")");
                        $data = $update_book->execute();
                    }
                }
                return $this->redirect(['/source/index',]);
            }
        }
        $id = $query['id'];
        $command = $conn->createCommand("select * from wechat_books where id in(".$id.") order by id desc");
        $data = $command->queryAll();
        return $this->render('push', [
            'model' => $model,
            'list' => $data,
            'id' => $id
        ]);
    }
    //图片函数
    public function setImageInformation($image){
        $pic_arr = [];
        foreach($image['file']['name'] as $key => $file){
            $name = $file;
            $arr = explode('.',$name);
            $ext = $arr[count($arr)-1];
            $path = Yii::$app->basePath .'/web/upload_files/'.date("YmdHis").mt_rand(1,9999).".".$ext;
            move_uploaded_file($image['file']['tmp_name'][$key],$path);
            $pic_arr[$key] = $path;
        }
        return $pic_arr;
    }
    //图片函数
    public function actionGet(){
        $webservice= new Webservice();
        $data = $webservice->GetNewBooks();
        //print_r($data);
        //print_r($data->GetNewBooksResult);exit;
        $status = "<span style='color:red;'>获取失败</span>";
        if($data->GetNewBooksResult->Result=='1'){
            $list = $data->GetNewBooksResult->Books->New;
            $time = time();
            foreach ($list as $key => $value) {
                $sql[] = "('".$value->Title."','".$value->BarCode."','".$value->Author."','".$value->ISBN."','".strtotime($value->Date)."','".$time."')";
                $barcode[] = "'".$value->BarCode."'";
            }

            $conn = Yii::$app->db;
            $search_sql = "SELECT * FROM wechat_books WHERE barcode in (".implode(',',$barcode).")";
            $command = $conn->createCommand($search_sql);
            $num = $command->queryAll();
            if(count($num)==0){
                $book_sql = "INSERT INTO wechat_books (name,barcode,author,isbn,date,time) VALUES ".implode(',',$sql);
                $command = $conn->createCommand($book_sql);
                $data = $command->execute();
                $status = "<span style='color:#449d44;'>获取成功</span>";
                return $this->redirect(['/book/index','status'=>$status]);
            }else{
                $status = "<span style='color:#999999;'>暂无新书</span>";
                return $this->redirect(['/book/index','status'=>$status]);
            }
        }
        return $this->redirect(['/book/index','status'=>$status]);
    }
}