<?php
/**
 * Created by PhpStorm.
 * User: Sam
 * Date: 2017/1/4
 * Time: 下午9:06
 */

namespace backend\controllers;

use Yii;
use yii\data\SqlDataProvider;
use yii\web\Controller;
use yii\grid\GridView;
use app\models\Notice;
use app\models\Books;
use yii\web\UploadedFile;
//微信框架引入方式
include dirname(dirname(__FILE__)).'/libs/LaneWeChat/lanewechat.php';
include dirname(dirname(__FILE__)).'/libs/LaneWeChat/core/source.lib.php';
include dirname(dirname(__FILE__)).'/libs/LaneWeChat/core/templatemessage.lib.php';
include dirname(dirname(__FILE__)).'/libs/LaneWeChat/core/advancedbroadcast.lib.php';
include dirname(dirname(__FILE__)).'/libs/LaneWeChat/core/responseinitiative.lib.php';
include dirname(dirname(__FILE__)).'/libs/LaneWeChat/core/usermanage.lib.php';
class NoticeController extends Controller
{

    public function beforeAction($action)
    {
        if (empty(Yii::$app->user->identity)) {
            return $this->redirect(['/default/login']);
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $this->layout = 'main';
        $searchModel = new Notice();
        $query = Yii::$app->request->queryParams;
        $sql_parms = 'where 1=1';
        if (!empty($query['Notice']['title'])) {
            $sql_parms .= " and title like '%" . $query['Notice']['title'] . "%'";
        }

        $sql = "select * from wechat_notice  " . $sql_parms . " order by id desc";
        $command = Yii::$app->db->createCommand('SELECT COUNT(*) FROM wechat_notice ' . $sql_parms);
        $count = $command->queryScalar();

        $dataProvider = new SqlDataProvider([
            'sql' => $sql,
            'totalCount' => $count,
            'pagination' => [
                'pageSize' => 15,
            ],
            'sort' => [
                'attributes' => [
                    'id',
                ],
            ],
        ]);

        GridView::widget([
            'dataProvider' => $dataProvider,
        ]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'query' => $query,
        ]);
    }

    public function actionDelete()
    {
        $query = Yii::$app->request->queryParams;
        $id = $query['id'];
        $data = Books::findOne($id);
        $data->delete();
        Yii::$app->cache->delete('index');
        return $this->redirect(['index']);
    }
    public function actionView()
    {
        $query = Yii::$app->request->queryParams;
        $list =  array();
        $error = "暂无数据";
        if(!empty($query['id'])){
            $conn = Yii::$app->db;
            $sql = "select * from wechat_books where n_id =".$query['id']." order by id desc";
            $command = $conn->createCommand($sql);
            $list = $command->queryAll();
        }else{
            $error = "数据出错";
        }
        return $this->render('view',[
            'list' => $list,
            'error' => $error
        ]);
    }
}