<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "video_shoot".
 *
 * @property integer $id
 * @property string $recordname
 * @property string $time
 * @property string $time1
 * @property double $capture_time
 * @property string $uploadname
 * @property integer $seat
 * @property string $projectname
 * @property string $school
 * @property string $courcename
 * @property string $teacher
 * @property string $status
 * @property string $auditor1
 * @property string $auditor2
 * @property integer $cid
 */
class VideoShoot extends \yii\db\ActiveRecord
{
    public $imageFiles;
    private $pic_name;
    public $time2;
    public $time1;
    public $test;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'video_shoot';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['test','capture_time'], 'number'],
            [['seat', 'cid','status','time_int','pid'], 'integer'],
            [['time2','recordname', 'time', 'time1', 'uploadname', 'projectname', 'school', 'courcename', 'teacher','remark'], 'string', 'max' => 100],
            [['imageFiles'], 'file', 'maxFiles' => 14],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'recordname' => '录制人 *',
            'time' => '拍摄时间 *',
            'capture_time' => '拍摄时长 *',
            'uploadname' => '上传人 *',
            'seat' => '机位个数 *',
            'projectname' => '项目名称 *',
            'school' => '学校 *',
            'courcename' => '课程名称 *',
            'teacher' => '主讲人 *',
            'status' => '审核',
            'remark' => '备注',
            'cid' => 'Cid',
            'pud' => 'Pid',
            'imageFiles' => '图片 *',
        ];
    }

    // videoshoot 表存入数据后 把图片存入pic表
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        $shoot_id = $this->id;

        if ($this->imageFiles) {
            foreach ($this->imageFiles as $k => $v) {
                $pic_model = new ShootPic();
                $pic_name = $v->name;
                $this->pic_name = $v->name;
                $type = strpos($pic_name, '.jpg') === false ? '.png' : '.jpg';
                $path = 'upload_files/videoshoot/' . date("Y-m-d-H-i-s") . '_' . $k . $type ;
                $pic_model->setAttributes([
                    'name' => $pic_name,
                    'path' => $path,
                    'shoot_id' => $shoot_id,
                ]);
                $pic_model->save();
//                $v->saveAs(dirname(__DIR__) . '\\web\\' . $path);
                $v->saveAs($path);
            }
        }
    }
}
